version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: unie
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: postgresql://root:root@db:5432/unie
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_DB_NAME: unie
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - postgres-network
    links:
      - "db:database"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgadmin-data:
  postgres-data:
  nginx-logs:

networks:
  postgres-network:
    driver: bridge
